### ISSUE TITLE
Html report break sonar UI

### ISSUE THREAD

**Issue by sysmat** [dependency-check/dependency-check-sonar-plugin#188]
**Describe the bug**

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install '...'
2. Run '....'
3. Login to '....'

**Current behavior**
When clicking on html report it put another frame of sonar. 
Links to external resources not working

**Expected behavior**
Same navigation as stand alone html report build by  maven plugin org.owasp:dependency-check-maven:5.2.4

**Screenshots**

**Versions (please complete the following information):**

-   dependency-check: 5.2.4
-   sonarqube: 8
-   dependency-check-sonar-plugin: 1.2.6

**Additional context**

![Sonar](https://user-images.githubusercontent.com/69830/69314599-d7687000-0c34-11ea-990a-6cf427be2a0d.png)

**Comment by Reamer** [comment]
Hi @sysmat,
can you check, if the [pre-release](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/tag/2.0.3-SNAPSHOT) solves your issue. This pre-release is based on [rewrite_javascript branch](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/rewrite_javascript).

**Comment by Vampire** [comment]
With 2.0.2 (+ fix for not showing the report at all) I do not see this behavior, but each time you select the report it adds another iframe, so you have the report shown multiple times.

For the external links to work, add `allow-popups` to the `sandbox` attribute.

So to fix the two issues I see in the current script, replace
```
var reportFrame = document.createElement("iframe");
reportFrame.sandbox.value = "allow-scripts allow-same-origin";
``` 
by
```
var reportFrame = document.getElementById("reportFrame");
if (!reportFrame) {
        reportFrame = document.createElement("iframe");
}
reportFrame.id = "reportFrame";
reportFrame.sandbox.value = "allow-scripts allow-same-origin allow-popups";
```
and it should work.

**Comment by Vampire** [comment]
The pre-release fixes the report being added multiple times, and external links working, but the styling of the report is broken and the scripts, for example to toggle things do not work.

**Comment by Reamer** [comment]
Fixed by #221

**Comment by bpapez** [comment]
We are using version 2.0.7 of the plugin and are still seeing the problem of opening additional iframes when clicking on the internal link of a dependency. We expect to get scrolled down in the page to the dependency details, but instead an iframe is opened and we are not scrolled down.

**Comment by Reamer** [comment]
@bpapez Please open a new issue. A screenshot would also be helpful. Please note that Internet Explorer is not supported.
